typography_spectrum: 0.7909627564450598
color:
  brandStrength: 0.23011990223734613
  lightness: 0.16117268499752305
  saturation: 0.5259698980006546
  rhythmicContrast: 0.43664187779668534
  brandColors:
    - '#DDDCC5'
    - '#958976'
    - '#611427'
    - '#1D2326'
    - '#6A6A61'
github: true
layout_spectrum: 0.3056346418349865
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8862b1dd-6cbf-4c06-a033-188275a35ce5.png
name: 'Sales, Solicitors and Independent Contractors Union'
navigation:
  - name: About Us
    url: 'https://yakurylander.wordpress.com/about/'
    type: external
  - name: Discussion
    url: 'https://yakurylander.wordpress.com/discussions/'
    type: external
  - name: Member Services Sign Up
    url: 'https://yakurylander.wordpress.com'
    type: external
  - name: Free Legal Service
    url: 'https://yakurylander.wordpress.com/2016/11/29/free-legal-service-updates/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/16dcdb45-e5e2-4a20-9ea0-1cb560476b76.png
title: SSIC-U
content: []
description: >-
  The Sales, Solicitors and Independent Contractors Union is constructed on the
  need to strengthen the sales agents and ensure fairness for the overlooked
  hard working men and women who are still without a place to turn to for help.
  Sales and Independent contractors are still one of the few fields that is
  without the protection of the NLRB.
purpose:
  - type: external
    url: 'https://yakurylander.wordpress.com/member-services/'
    label: Join Today
  - type: external
    url: 'https://yakurylander.wordpress.com/discussions/'
    label: Discussions
